CREATE TABLE IF NOT EXISTS public.votes
(
  voteid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  created_at timestamp with time zone DEFAULT now(),
  github_user_id bigint,
  repo_name text COLLATE pg_catalog."default",
  vote_code text COLLATE pg_catalog."default",
  CONSTRAINT votes_pkey PRIMARY KEY (voteid),
  CONSTRAINT votes_votes_received_key UNIQUE (vote_code)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.votes
  OWNER to supabase_admin;

GRANT ALL ON TABLE public.votes TO anon;

GRANT ALL ON TABLE public.votes TO authenticated;

GRANT ALL ON TABLE public.votes TO postgres;

GRANT ALL ON TABLE public.votes TO service_role;

GRANT ALL ON TABLE public.votes TO supabase_admin;

COMMENT ON TABLE public.votes
  IS 'A collection of votes fro users';

CREATE POLICY "Enable access to all users"
  ON public.votes
  AS PERMISSIVE
  FOR ALL
  TO public
  USING (true);
