-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.stars
(
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  stargazers_count bigint NOT NULL DEFAULT 0,
  open_issues_count bigint NOT NULL DEFAULT 0,
  forks_count bigint NOT NULL DEFAULT 0,
  full_name text COLLATE pg_catalog."default" NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stars_pkey PRIMARY KEY (id),
  CONSTRAINT stars_full_name_key UNIQUE (full_name)
)

  TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.stars
  OWNER to postgres;

GRANT ALL ON TABLE public.stars TO anon;

GRANT ALL ON TABLE public.stars TO authenticated;

GRANT ALL ON TABLE public.stars TO postgres;

GRANT ALL ON TABLE public.stars TO service_role;

GRANT ALL ON TABLE public.stars TO supabase_admin;
