CREATE TABLE IF NOT EXISTS public.user_stars
(
  star_id bigint NOT NULL,
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  user_id bigint NOT NULL,
  repo_name text COLLATE pg_catalog."default",
  recency_score smallint,
  description text COLLATE pg_catalog."default",
  issues bigint,
  stars bigint,
  contributors text[] COLLATE pg_catalog."default",
  CONSTRAINT user_stars_duplicate_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_stars
  OWNER to supabase_admin;

GRANT ALL ON TABLE public.user_stars TO anon;

GRANT ALL ON TABLE public.user_stars TO authenticated;

GRANT ALL ON TABLE public.user_stars TO postgres;

GRANT ALL ON TABLE public.user_stars TO service_role;

GRANT ALL ON TABLE public.user_stars TO supabase_admin;

COMMENT ON COLUMN public.user_stars.recency_score
  IS 'Lower number means it was starred recently';

COMMENT ON COLUMN public.user_stars.description
  IS 'Description of the repository';

COMMENT ON COLUMN public.user_stars.issues
  IS 'Total amount of issues';

COMMENT ON COLUMN public.user_stars.stars
  IS 'Total amount of stars for the repository';

COMMENT ON COLUMN public.user_stars.contributors
  IS 'array of contributor names';
