-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.recommendations
(
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  stars bigint NOT NULL DEFAULT 0,
  issues bigint NOT NULL DEFAULT 0,
  total_stars bigint NOT NULL DEFAULT 0,
  votes bigint NOT NULL DEFAULT 0,
  avg_recency_score numeric,
  repo_name text COLLATE pg_catalog."default",
  description text COLLATE pg_catalog."default",
  contributors text[] COLLATE pg_catalog."default",
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT recommendations_pkey PRIMARY KEY (id)
)

  TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recommendations
  OWNER to postgres;

GRANT ALL ON TABLE public.recommendations TO anon;

GRANT ALL ON TABLE public.recommendations TO authenticated;

GRANT ALL ON TABLE public.recommendations TO postgres;

GRANT ALL ON TABLE public.recommendations TO service_role;

GRANT ALL ON TABLE public.recommendations TO supabase_admin;
