name: Compliance

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

permissions:
  pull-requests: write

jobs:
  semantics:
    name: Semantics
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-compliance-checks:
    name: PR Compliance Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: mtfoley/pr-compliance-action@v0.5.0
        with:
          body-auto-close: false
          protected-branch-auto-close: false
          watch-files: |
            package.json
            package-lock.json
            npm-shrinkwrap.json
          body-comment: >
            ## Issue Reference

            In order to be considered for merging, the pull request description must refer to a
            specific issue number. This is described in our
            [Contributing Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/).

            This check is looking for a phrase similar to: "Fixes #XYZ" or "Resolves #XYZ" where XYZ is the issue
            number that this PR is meant to address.
          protected-branch-comment: >
            ## Protected Branch

            In order to be considered for merging, the pull request changes must
            not be implemented on the "%branch%" branch. This is described in our
            [Contributing Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/).
            We would suggest that you close this PR and implement your changes as
            described in our Contributing Guide and open a new pull request.

  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: semantics
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Congrats on making your first Pull Request and thanks for taking the time to improve Open Sauced! ❤️! 🎉🍕
            Say hello by joining the conversation in our [Discord](https://discord.gg/U2peSNf23P)
